// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: environment_variables.sql

package database

import (
	"context"
	"database/sql"
)

const checkEnvironmentVariableNameExists = `-- name: CheckEnvironmentVariableNameExists :one
SELECT COUNT(*) FROM environment_variables 
WHERE name = ?
`

func (q *Queries) CheckEnvironmentVariableNameExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEnvironmentVariableNameExists, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEnvironmentVariable = `-- name: CreateEnvironmentVariable :one

INSERT INTO environment_variables (id, name, value, description)
VALUES (?, ?, ?, ?)
RETURNING id, name, value, description, created_at, updated_at
`

type CreateEnvironmentVariableParams struct {
	ID          string
	Name        string
	Value       string
	Description sql.NullString
}

// Environment Variables queries
func (q *Queries) CreateEnvironmentVariable(ctx context.Context, arg CreateEnvironmentVariableParams) (EnvironmentVariable, error) {
	row := q.db.QueryRowContext(ctx, createEnvironmentVariable,
		arg.ID,
		arg.Name,
		arg.Value,
		arg.Description,
	)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEnvironmentVariable = `-- name: DeleteEnvironmentVariable :exec
DELETE FROM environment_variables 
WHERE id = ?
`

func (q *Queries) DeleteEnvironmentVariable(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteEnvironmentVariable, id)
	return err
}

const getEnvironmentVariable = `-- name: GetEnvironmentVariable :one
SELECT id, name, value, description, created_at, updated_at FROM environment_variables 
WHERE id = ?
`

func (q *Queries) GetEnvironmentVariable(ctx context.Context, id string) (EnvironmentVariable, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentVariable, id)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEnvironmentVariableByName = `-- name: GetEnvironmentVariableByName :one
SELECT id, name, value, description, created_at, updated_at FROM environment_variables 
WHERE name = ?
`

func (q *Queries) GetEnvironmentVariableByName(ctx context.Context, name string) (EnvironmentVariable, error) {
	row := q.db.QueryRowContext(ctx, getEnvironmentVariableByName, name)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnvironmentVariables = `-- name: ListEnvironmentVariables :many
SELECT id, name, value, description, created_at, updated_at FROM environment_variables 
ORDER BY name
`

func (q *Queries) ListEnvironmentVariables(ctx context.Context) ([]EnvironmentVariable, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentVariables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentVariable
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchEnvironmentVariablesByName = `-- name: SearchEnvironmentVariablesByName :many
SELECT id, name, value, description, created_at, updated_at FROM environment_variables 
WHERE name LIKE ?
ORDER BY name
`

func (q *Queries) SearchEnvironmentVariablesByName(ctx context.Context, name string) ([]EnvironmentVariable, error) {
	rows, err := q.db.QueryContext(ctx, searchEnvironmentVariablesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EnvironmentVariable
	for rows.Next() {
		var i EnvironmentVariable
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Value,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEnvironmentVariable = `-- name: UpdateEnvironmentVariable :one
UPDATE environment_variables 
SET name = ?, value = ?, description = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, value, description, created_at, updated_at
`

type UpdateEnvironmentVariableParams struct {
	Name        string
	Value       string
	Description sql.NullString
	ID          string
}

func (q *Queries) UpdateEnvironmentVariable(ctx context.Context, arg UpdateEnvironmentVariableParams) (EnvironmentVariable, error) {
	row := q.db.QueryRowContext(ctx, updateEnvironmentVariable,
		arg.Name,
		arg.Value,
		arg.Description,
		arg.ID,
	)
	var i EnvironmentVariable
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Value,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
