// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: executions.sql

package database

import (
	"context"
	"database/sql"
)

const cleanupOldExecutions = `-- name: CleanupOldExecutions :exec
DELETE FROM executions
WHERE finished_at < datetime('now', '-30 days')
AND status IN ('success', 'failed', 'cancelled')
`

func (q *Queries) CleanupOldExecutions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, cleanupOldExecutions)
	return err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (
    id, recipe_id, status, input_data, execution_context
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context
`

type CreateExecutionParams struct {
	ID               string
	RecipeID         string
	Status           string
	InputData        string
	ExecutionContext string
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, createExecution,
		arg.ID,
		arg.RecipeID,
		arg.Status,
		arg.InputData,
		arg.ExecutionContext,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.InputData,
		&i.OutputData,
		&i.ExecutionContext,
	)
	return i, err
}

const deleteExecution = `-- name: DeleteExecution :exec
DELETE FROM executions
WHERE id = ?
`

func (q *Queries) DeleteExecution(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteExecution, id)
	return err
}

const getExecution = `-- name: GetExecution :one
SELECT id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions
WHERE id = ? LIMIT 1
`

func (q *Queries) GetExecution(ctx context.Context, id string) (Execution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.InputData,
		&i.OutputData,
		&i.ExecutionContext,
	)
	return i, err
}

const getExecutionStats = `-- name: GetExecutionStats :one
SELECT 
    COUNT(*) as total_executions,
    COUNT(CASE WHEN status = 'success' THEN 1 END) as successful_executions,
    COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed_executions,
    COUNT(CASE WHEN status = 'cancelled' THEN 1 END) as cancelled_executions,
    COUNT(CASE WHEN status = 'running' THEN 1 END) as running_executions,
    AVG(CASE WHEN status = 'success' THEN duration_ms END) as avg_success_duration_ms
FROM executions
WHERE recipe_id = ?
`

type GetExecutionStatsRow struct {
	TotalExecutions      int64
	SuccessfulExecutions int64
	FailedExecutions     int64
	CancelledExecutions  int64
	RunningExecutions    int64
	AvgSuccessDurationMs sql.NullFloat64
}

func (q *Queries) GetExecutionStats(ctx context.Context, recipeID string) (GetExecutionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionStats, recipeID)
	var i GetExecutionStatsRow
	err := row.Scan(
		&i.TotalExecutions,
		&i.SuccessfulExecutions,
		&i.FailedExecutions,
		&i.CancelledExecutions,
		&i.RunningExecutions,
		&i.AvgSuccessDurationMs,
	)
	return i, err
}

const getExecutionsByRecipeAndStatus = `-- name: GetExecutionsByRecipeAndStatus :many
SELECT id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions
WHERE recipe_id = ? AND status = ?
ORDER BY started_at DESC
`

type GetExecutionsByRecipeAndStatusParams struct {
	RecipeID string
	Status   string
}

func (q *Queries) GetExecutionsByRecipeAndStatus(ctx context.Context, arg GetExecutionsByRecipeAndStatusParams) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByRecipeAndStatus, arg.RecipeID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentExecutions = `-- name: GetRecentExecutions :many
SELECT id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions
WHERE started_at >= datetime('now', '-7 days')
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) GetRecentExecutions(ctx context.Context, limit int64) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getRecentExecutions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningExecutions = `-- name: GetRunningExecutions :many
SELECT id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions
WHERE status = 'running'
ORDER BY started_at DESC
`

func (q *Queries) GetRunningExecutions(ctx context.Context) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getRunningExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutions = `-- name: ListExecutions :many
SELECT id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions
ORDER BY started_at DESC
`

func (q *Queries) ListExecutions(ctx context.Context) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsByRecipe = `-- name: ListExecutionsByRecipe :many
SELECT id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions
WHERE recipe_id = ?
ORDER BY started_at DESC
`

func (q *Queries) ListExecutionsByRecipe(ctx context.Context, recipeID string) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionsByRecipe, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExecutionsByStatus = `-- name: ListExecutionsByStatus :many
SELECT id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions
WHERE status = ?
ORDER BY started_at DESC
`

func (q *Queries) ListExecutionsByStatus(ctx context.Context, status string) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, listExecutionsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.RecipeID,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE executions
SET 
    status = ?1,
    finished_at = CASE 
        WHEN ?1 IN ('success', 'failed', 'cancelled') THEN CURRENT_TIMESTAMP 
        ELSE finished_at 
    END,
    duration_ms = CASE 
        WHEN ?1 IN ('success', 'failed', 'cancelled') 
        THEN CAST((julianday(CURRENT_TIMESTAMP) - julianday(started_at)) * 86400000 AS INTEGER)
        ELSE duration_ms 
    END,
    error_message = ?2,
    output_data = ?3
WHERE id = ?4
RETURNING id, recipe_id, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context
`

type UpdateExecutionStatusParams struct {
	Status       string
	ErrorMessage string
	OutputData   string
	ID           string
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, updateExecutionStatus,
		arg.Status,
		arg.ErrorMessage,
		arg.OutputData,
		arg.ID,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.InputData,
		&i.OutputData,
		&i.ExecutionContext,
	)
	return i, err
}
