// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Credential struct {
	ID            string
	Name          string
	Type          string
	Description   sql.NullString
	KeychainKey   sql.NullString
	EncryptedData []byte
	Salt          []byte
	StorageType   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastUsedAt    sql.NullTime
}

type EnvironmentVariable struct {
	ID          string
	Name        string
	Value       string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Execution struct {
	ID               string
	RecipeID         string
	Status           string
	StartedAt        time.Time
	FinishedAt       sql.NullTime
	DurationMs       sql.NullInt64
	ErrorMessage     string
	InputData        string
	OutputData       string
	ExecutionContext string
}

type Recipe struct {
	ID          string
	Name        string
	Description string
	RecipePath  string
	Tags        string
	NodeTypes   string
	NodeCount   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Setting struct {
	ID        int64
	Theme     string
	AutoStart int64
	Language  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
