// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recipes.sql

package database

import (
	"context"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
    id, name, description, recipe_path, tags, node_types, node_count
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, description, recipe_path, tags, node_types, node_count, created_at, updated_at
`

type CreateRecipeParams struct {
	ID          string
	Name        string
	Description string
	RecipePath  string
	Tags        string
	NodeTypes   string
	NodeCount   int64
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RecipePath,
		arg.Tags,
		arg.NodeTypes,
		arg.NodeCount,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.Tags,
		&i.NodeTypes,
		&i.NodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, id)
	return err
}

const existsRecipeByPath = `-- name: ExistsRecipeByPath :one
SELECT COUNT(*) = 1 FROM recipes
WHERE recipe_path = ?
`

func (q *Queries) ExistsRecipeByPath(ctx context.Context, recipePath string) (bool, error) {
	row := q.db.QueryRowContext(ctx, existsRecipeByPath, recipePath)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, name, description, recipe_path, tags, node_types, node_count, created_at, updated_at FROM recipes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.Tags,
		&i.NodeTypes,
		&i.NodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeByPath = `-- name: GetRecipeByPath :one
SELECT id, name, description, recipe_path, tags, node_types, node_count, created_at, updated_at FROM recipes
WHERE recipe_path = ?
LIMIT 1
`

func (q *Queries) GetRecipeByPath(ctx context.Context, recipePath string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByPath, recipePath)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.Tags,
		&i.NodeTypes,
		&i.NodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeIdByPath = `-- name: GetRecipeIdByPath :one
SELECT id FROM recipes
WHERE recipe_path = ?
`

func (q *Queries) GetRecipeIdByPath(ctx context.Context, recipePath string) (string, error) {
	row := q.db.QueryRowContext(ctx, getRecipeIdByPath, recipePath)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, name, description, recipe_path, tags, node_types, node_count, created_at, updated_at FROM recipes
ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RecipePath,
			&i.Tags,
			&i.NodeTypes,
			&i.NodeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipesByName = `-- name: SearchRecipesByName :many
SELECT id, name, description, recipe_path, tags, node_types, node_count, created_at, updated_at FROM recipes
WHERE name LIKE ?
ORDER BY created_at DESC
`

func (q *Queries) SearchRecipesByName(ctx context.Context, name string) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, searchRecipesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RecipePath,
			&i.Tags,
			&i.NodeTypes,
			&i.NodeCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET 
    name = ?,
    description = ?,
    tags = ?,
    node_types = ?,
    node_count = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, recipe_path, tags, node_types, node_count, created_at, updated_at
`

type UpdateRecipeParams struct {
	Name        string
	Description string
	Tags        string
	NodeTypes   string
	NodeCount   int64
	ID          string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.NodeTypes,
		arg.NodeCount,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.Tags,
		&i.NodeTypes,
		&i.NodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecipeByPath = `-- name: UpdateRecipeByPath :one
UPDATE recipes
SET 
    name = ?,
    description = ?,
    tags = ?,
    node_types = ?,
    node_count = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE recipe_path = ?
RETURNING id, name, description, recipe_path, tags, node_types, node_count, created_at, updated_at
`

type UpdateRecipeByPathParams struct {
	Name        string
	Description string
	Tags        string
	NodeTypes   string
	NodeCount   int64
	RecipePath  string
}

func (q *Queries) UpdateRecipeByPath(ctx context.Context, arg UpdateRecipeByPathParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipeByPath,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.NodeTypes,
		arg.NodeCount,
		arg.RecipePath,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.Tags,
		&i.NodeTypes,
		&i.NodeCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
