// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package database

import (
	"context"
)

const createDefaultSettings = `-- name: CreateDefaultSettings :exec
INSERT INTO settings (id, theme, auto_start, language) 
VALUES (1, 'system', 0, 'en')
ON CONFLICT(id) DO NOTHING
`

func (q *Queries) CreateDefaultSettings(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, createDefaultSettings)
	return err
}

const getOrCreateSettings = `-- name: GetOrCreateSettings :one
INSERT INTO settings (id, theme, auto_start, language) 
VALUES (1, 'system', 0, 'en')
ON CONFLICT(id) DO UPDATE SET
    id = excluded.id
RETURNING id, theme, auto_start, language, created_at, updated_at
`

func (q *Queries) GetOrCreateSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Theme,
		&i.AutoStart,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, theme, auto_start, language, created_at, updated_at FROM settings LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.Theme,
		&i.AutoStart,
		&i.Language,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAutoStart = `-- name: UpdateAutoStart :exec
UPDATE settings 
SET auto_start = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = 1
`

func (q *Queries) UpdateAutoStart(ctx context.Context, autoStart bool) error {
	_, err := q.db.ExecContext(ctx, updateAutoStart, autoStart)
	return err
}

const updateLanguage = `-- name: UpdateLanguage :exec
UPDATE settings 
SET language = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = 1
`

func (q *Queries) UpdateLanguage(ctx context.Context, language string) error {
	_, err := q.db.ExecContext(ctx, updateLanguage, language)
	return err
}

const updateSettings = `-- name: UpdateSettings :exec
UPDATE settings 
SET theme = ?, 
    auto_start = ?, 
    language = ?,
    updated_at = CURRENT_TIMESTAMP 
WHERE id = 1
`

type UpdateSettingsParams struct {
	Theme     string
	AutoStart bool
	Language  string
}

func (q *Queries) UpdateSettings(ctx context.Context, arg UpdateSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSettings, arg.Theme, arg.AutoStart, arg.Language)
	return err
}

const updateTheme = `-- name: UpdateTheme :exec
UPDATE settings 
SET theme = ?, updated_at = CURRENT_TIMESTAMP 
WHERE id = 1
`

func (q *Queries) UpdateTheme(ctx context.Context, theme string) error {
	_, err := q.db.ExecContext(ctx, updateTheme, theme)
	return err
}
