// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * EnvironmentVariablesService provides environment variable management functionality to the frontend.
 * It handles CRUD operations for non-sensitive configuration data stored in plaintext.
 * 
 * Environment variables are used for configuration data that doesn't require encryption,
 * such as API base URLs, timeouts, and other application settings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateEnvironmentVariable creates a new environment variable with the provided data.
 * 
 * Returns an error if:
 * - An environment variable with the same name already exists
 * - Database operation fails
 */
export function CreateEnvironmentVariable(req: $models.EnvironmentVariableCreateRequest): $CancellablePromise<$models.EnvironmentVariableInfo | null> {
    return $Call.ByID(366048161, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteEnvironmentVariable removes an environment variable from storage permanently.
 */
export function DeleteEnvironmentVariable(id: string): $CancellablePromise<void> {
    return $Call.ByID(752951872, id);
}

/**
 * GetEnvironmentVariable retrieves an environment variable by ID.
 */
export function GetEnvironmentVariable(id: string): $CancellablePromise<$models.EnvironmentVariableInfo | null> {
    return $Call.ByID(3994878145, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetEnvironmentVariableValue retrieves a specific environment variable value by name.
 */
export function GetEnvironmentVariableValue(name: string): $CancellablePromise<string> {
    return $Call.ByID(2937754830, name);
}

/**
 * ListEnvironmentVariables returns all environment variables.
 */
export function ListEnvironmentVariables(): $CancellablePromise<$models.EnvironmentVariableInfo[]> {
    return $Call.ByID(2941860482).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SearchEnvironmentVariables searches for environment variables by name pattern.
 */
export function SearchEnvironmentVariables(pattern: string): $CancellablePromise<$models.EnvironmentVariableInfo[]> {
    return $Call.ByID(2597387118, pattern).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * UpdateEnvironmentVariable updates an existing environment variable with new data.
 */
export function UpdateEnvironmentVariable(req: $models.EnvironmentVariableUpdateRequest): $CancellablePromise<$models.EnvironmentVariableInfo | null> {
    return $Call.ByID(2642444022, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.EnvironmentVariableInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType0);
