// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recipe$0 from "../internal/recipe/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../time/models.js";

export class CreatedRecipe {
    "Recipe": recipe$0.Recipe | null;
    "ID": string;

    /** Creates a new CreatedRecipe instance. */
    constructor($$source: Partial<CreatedRecipe> = {}) {
        if (!("Recipe" in $$source)) {
            this["Recipe"] = null;
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedRecipe instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedRecipe {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Recipe" in $$parsedSource) {
            $$parsedSource["Recipe"] = $$createField0_0($$parsedSource["Recipe"]);
        }
        return new CreatedRecipe($$parsedSource as Partial<CreatedRecipe>);
    }
}

export class EditSession {
    "id": string;
    "loaded_at": time$0.Time;
    "last_modified": time$0.Time;
    "needs_save": boolean;
    "recipe": recipe$0.Recipe | null;

    /** Creates a new EditSession instance. */
    constructor($$source: Partial<EditSession> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("loaded_at" in $$source)) {
            this["loaded_at"] = null;
        }
        if (!("last_modified" in $$source)) {
            this["last_modified"] = null;
        }
        if (!("needs_save" in $$source)) {
            this["needs_save"] = false;
        }
        if (!("recipe" in $$source)) {
            this["recipe"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EditSession instance from a string or object.
     */
    static createFrom($$source: any = {}): EditSession {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("recipe" in $$parsedSource) {
            $$parsedSource["recipe"] = $$createField4_0($$parsedSource["recipe"]);
        }
        return new EditSession($$parsedSource as Partial<EditSession>);
    }
}

/**
 * EnvironmentVariableCreateRequest represents the data needed to create a new environment variable.
 */
export class EnvironmentVariableCreateRequest {
    "name": string;
    "value": string;
    "description": string;

    /** Creates a new EnvironmentVariableCreateRequest instance. */
    constructor($$source: Partial<EnvironmentVariableCreateRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentVariableCreateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvironmentVariableCreateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentVariableCreateRequest($$parsedSource as Partial<EnvironmentVariableCreateRequest>);
    }
}

/**
 * EnvironmentVariableInfo represents basic environment variable information.
 */
export class EnvironmentVariableInfo {
    "id": string;
    "name": string;
    "value": string;
    "description": string;
    "created_at": string;
    "updated_at": string;

    /** Creates a new EnvironmentVariableInfo instance. */
    constructor($$source: Partial<EnvironmentVariableInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentVariableInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvironmentVariableInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentVariableInfo($$parsedSource as Partial<EnvironmentVariableInfo>);
    }
}

/**
 * EnvironmentVariableUpdateRequest represents the data needed to update an existing environment variable.
 */
export class EnvironmentVariableUpdateRequest {
    "id": string;
    "name": string;
    "value": string;
    "description": string;

    /** Creates a new EnvironmentVariableUpdateRequest instance. */
    constructor($$source: Partial<EnvironmentVariableUpdateRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EnvironmentVariableUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): EnvironmentVariableUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new EnvironmentVariableUpdateRequest($$parsedSource as Partial<EnvironmentVariableUpdateRequest>);
    }
}

export class RecipeInfo {
    "ID": string;
    "Name": string;
    "Description": string;
    "RecipePath": string;
    "NodeCount": number;
    "CreatedAt": time$0.Time;
    "UpdatedAt": time$0.Time;
    "ExecutionCount": number;
    "LastExecution": time$0.Time;
    "LastExecutionStatus": string;
    "Tags": string[];
    "NodeTypes": string[];

    /** Creates a new RecipeInfo instance. */
    constructor($$source: Partial<RecipeInfo> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("RecipePath" in $$source)) {
            this["RecipePath"] = "";
        }
        if (!("NodeCount" in $$source)) {
            this["NodeCount"] = 0;
        }
        if (!("CreatedAt" in $$source)) {
            this["CreatedAt"] = null;
        }
        if (!("UpdatedAt" in $$source)) {
            this["UpdatedAt"] = null;
        }
        if (!("ExecutionCount" in $$source)) {
            this["ExecutionCount"] = 0;
        }
        if (!("LastExecution" in $$source)) {
            this["LastExecution"] = null;
        }
        if (!("LastExecutionStatus" in $$source)) {
            this["LastExecutionStatus"] = "";
        }
        if (!("Tags" in $$source)) {
            this["Tags"] = [];
        }
        if (!("NodeTypes" in $$source)) {
            this["NodeTypes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RecipeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): RecipeInfo {
        const $$createField10_0 = $$createType2;
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Tags" in $$parsedSource) {
            $$parsedSource["Tags"] = $$createField10_0($$parsedSource["Tags"]);
        }
        if ("NodeTypes" in $$parsedSource) {
            $$parsedSource["NodeTypes"] = $$createField11_0($$parsedSource["NodeTypes"]);
        }
        return new RecipeInfo($$parsedSource as Partial<RecipeInfo>);
    }
}

/**
 * SecretCreateRequest represents the data needed to create a new secret.
 */
export class SecretCreateRequest {
    "name": string;
    "description": string;
    "value": string;

    /** Creates a new SecretCreateRequest instance. */
    constructor($$source: Partial<SecretCreateRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecretCreateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SecretCreateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecretCreateRequest($$parsedSource as Partial<SecretCreateRequest>);
    }
}

/**
 * SecretInfo represents basic secret information without sensitive data.
 * Used for listing and displaying secrets in the UI safely.
 */
export class SecretInfo {
    "id": string;
    "name": string;
    "description": string;
    "storage_type": string;
    "created_at": string;
    "updated_at": string;
    "last_used_at": string;

    /** Creates a new SecretInfo instance. */
    constructor($$source: Partial<SecretInfo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("storage_type" in $$source)) {
            this["storage_type"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("updated_at" in $$source)) {
            this["updated_at"] = "";
        }
        if (!("last_used_at" in $$source)) {
            this["last_used_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecretInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SecretInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecretInfo($$parsedSource as Partial<SecretInfo>);
    }
}

/**
 * SecretUpdateRequest represents the data needed to update an existing secret.
 */
export class SecretUpdateRequest {
    "id": string;
    "name": string;
    "description": string;
    "value": string;

    /** Creates a new SecretUpdateRequest instance. */
    constructor($$source: Partial<SecretUpdateRequest> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecretUpdateRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): SecretUpdateRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecretUpdateRequest($$parsedSource as Partial<SecretUpdateRequest>);
    }
}

/**
 * SecretValueResponse contains a decrypted secret value.
 * Used for retrieving specific secret values for workflow execution.
 */
export class SecretValueResponse {
    "value": string;
    "found": boolean;

    /** Creates a new SecretValueResponse instance. */
    constructor($$source: Partial<SecretValueResponse> = {}) {
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("found" in $$source)) {
            this["found"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SecretValueResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): SecretValueResponse {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SecretValueResponse($$parsedSource as Partial<SecretValueResponse>);
    }
}

// Private type creation functions
const $$createType0 = recipe$0.Recipe.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
