// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recipe$0 from "../internal/recipe/models.js";

export class CreatedRecipe {
    "Recipe": recipe$0.Recipe | null;
    "ID": string;

    /** Creates a new CreatedRecipe instance. */
    constructor($$source: Partial<CreatedRecipe> = {}) {
        if (!("Recipe" in $$source)) {
            this["Recipe"] = null;
        }
        if (!("ID" in $$source)) {
            this["ID"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreatedRecipe instance from a string or object.
     */
    static createFrom($$source: any = {}): CreatedRecipe {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Recipe" in $$parsedSource) {
            $$parsedSource["Recipe"] = $$createField0_0($$parsedSource["Recipe"]);
        }
        return new CreatedRecipe($$parsedSource as Partial<CreatedRecipe>);
    }
}

// Private type creation functions
const $$createType0 = recipe$0.Recipe.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
