// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as node$0 from "../internal/node/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as recipe$0 from "../internal/recipe/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CreateNode(ref: string, x: number, y: number): $CancellablePromise<recipe$0.Node> {
    return $Call.ByID(3354454747, ref, x, y).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateRecipe(name: string, description: string): $CancellablePromise<$models.CreatedRecipe | null> {
    return $Call.ByID(209478005, name, description).then(($result: any) => {
        return $$createType2($result);
    });
}

export function DeleteRecipe(id: string): $CancellablePromise<void> {
    return $Call.ByID(4118010790, id);
}

/**
 * ExecuteTriggerNode executes a single trigger node with provided arguments
 */
export function ExecuteTriggerNode(recipeID: string, nodeID: string, properties: { [_: string]: any }, args: { [_: string]: any }): $CancellablePromise<void> {
    return $Call.ByID(2828047122, recipeID, nodeID, properties, args);
}

export function GetAvailableNodes(): $CancellablePromise<node$0.NodeInfo[]> {
    return $Call.ByID(1184928677).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetAvailableNodesByType(nodeType: string): $CancellablePromise<node$0.NodeInfo[]> {
    return $Call.ByID(4244076764, nodeType).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetRecipe(id: string): $CancellablePromise<recipe$0.Recipe | null> {
    return $Call.ByID(493884671, id).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListRecipes(): $CancellablePromise<$models.RecipeInfo[]> {
    return $Call.ByID(590765802).then(($result: any) => {
        return $$createType8($result);
    });
}

export function RunRecipe(recipe: recipe$0.Recipe | null, startNodeId: string, properties: { [_: string]: any }): $CancellablePromise<void> {
    return $Call.ByID(226350490, recipe, startNodeId, properties);
}

export function RunRecipeByID(id: string, startNodeId: string, properties: { [_: string]: any }): $CancellablePromise<void> {
    return $Call.ByID(2955805230, id, startNodeId, properties);
}

export function SaveRecipe(id: string, recipe: recipe$0.Recipe | null): $CancellablePromise<recipe$0.Recipe | null> {
    return $Call.ByID(4266337316, id, recipe).then(($result: any) => {
        return $$createType6($result);
    });
}

export function Sync(): $CancellablePromise<void> {
    return $Call.ByID(197929644);
}

export function UpdateRecipe(id: string, recipe: recipe$0.Recipe | null): $CancellablePromise<void> {
    return $Call.ByID(960607656, id, recipe);
}

// Private type creation functions
const $$createType0 = recipe$0.Node.createFrom;
const $$createType1 = $models.CreatedRecipe.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = node$0.NodeInfo.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = recipe$0.Recipe.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $models.RecipeInfo.createFrom;
const $$createType8 = $Create.Array($$createType7);
