// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SecretsService provides secure secret management functionality to the frontend.
 * It handles CRUD operations for encrypted secrets including API keys, tokens,
 * and other sensitive data with support for multiple storage backends.
 * 
 * All sensitive data is automatically encrypted before storage and decrypted on retrieval.
 * The service is safe for concurrent use and provides validation for secret operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateSecret creates a new encrypted secret with the provided data.
 * The secret data is automatically encrypted using AES-256-GCM with a unique salt.
 * 
 * Returns an error if:
 * - A secret with the same name already exists
 * - The storage type is invalid
 * - Encryption fails
 * - Database operation fails
 */
export function CreateSecret(req: $models.SecretCreateRequest): $CancellablePromise<$models.SecretInfo | null> {
    return $Call.ByID(2955767437, req).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * DeleteSecret removes a secret from storage permanently.
 * This operation cannot be undone.
 * 
 * For keychain storage, this also removes the secret from the system keychain.
 */
export function DeleteSecret(id: string): $CancellablePromise<void> {
    return $Call.ByID(2431546390, id);
}

/**
 * GetAvailableStorageTypes returns a list of supported storage types.
 */
export function GetAvailableStorageTypes(): $CancellablePromise<string[]> {
    return $Call.ByID(1372760340).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetSecret retrieves a secret by ID with basic information only.
 * Sensitive data is not included in the response for security.
 * 
 * To retrieve decrypted secret data, use GetSecretValue.
 */
export function GetSecret(id: string): $CancellablePromise<$models.SecretInfo | null> {
    return $Call.ByID(3008946491, id).then(($result: any) => {
        return $$createType1($result);
    });
}

/**
 * GetSecretData retrieves and decrypts the value from a secret.
 * This method is primarily used for secret editing in the UI.
 * 
 * WARNING: This returns sensitive decrypted data. Use with caution.
 */
export function GetSecretData(id: string): $CancellablePromise<string> {
    return $Call.ByID(218059907, id);
}

/**
 * GetSecretValue retrieves and decrypts a specific secret by name.
 * This method marks the secret as used and updates the last_used_at timestamp.
 * 
 * Use this method for retrieving secret values during workflow execution.
 */
export function GetSecretValue(secretName: string): $CancellablePromise<$models.SecretValueResponse | null> {
    return $Call.ByID(2919186296, secretName).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetUnusedSecrets returns secrets that haven't been used recently.
 * Useful for cleanup and maintenance of stale secrets.
 */
export function GetUnusedSecrets(): $CancellablePromise<$models.SecretInfo[]> {
    return $Call.ByID(3158876554).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * ListSecrets returns all secrets with basic information only.
 * Sensitive data is not included in the response for security.
 * 
 * This method is safe to use in UI contexts where secret lists are displayed.
 */
export function ListSecrets(): $CancellablePromise<$models.SecretInfo[]> {
    return $Call.ByID(558500358).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * SearchSecrets searches for secrets by name pattern.
 * The pattern supports SQL LIKE syntax (% for wildcards).
 */
export function SearchSecrets(pattern: string): $CancellablePromise<$models.SecretInfo[]> {
    return $Call.ByID(2075680710, pattern).then(($result: any) => {
        return $$createType5($result);
    });
}

/**
 * UpdateSecret updates an existing secret with new data.
 * The secret data is re-encrypted with a new salt for enhanced security.
 * 
 * Returns an error if the secret doesn't exist or update fails.
 */
export function UpdateSecret(req: $models.SecretUpdateRequest): $CancellablePromise<$models.SecretInfo | null> {
    return $Call.ByID(3844765956, req).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.SecretInfo.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.SecretValueResponse.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType0);
