// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../internal/database/models.js";

export function GetSettings(): $CancellablePromise<database$0.Setting> {
    return $Call.ByID(982178404).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateSettings(settings: database$0.Setting): $CancellablePromise<void> {
    return $Call.ByID(203474747, settings);
}

export function UpdateTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(104893975, theme);
}

// Private type creation functions
const $$createType0 = database$0.Setting.createFrom;
