// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stores$0 from "../stores/models.js";

export function CreateNode(nodeId: string): $CancellablePromise<stores$0.Node> {
    return $Call.ByID(959909210, nodeId).then(($result: any) => {
        return $$createType0($result);
    });
}

export function GetNodeInfo(id: string): $CancellablePromise<stores$0.NodeInfo> {
    return $Call.ByID(3414493882, id).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetNodeInfos(): $CancellablePromise<stores$0.NodeInfo[]> {
    return $Call.ByID(728758891).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetNodeInfosByType(nodeType: string): $CancellablePromise<stores$0.NodeInfo[]> {
    return $Call.ByID(3388126950, nodeType).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetTeaTime(): $CancellablePromise<string> {
    return $Call.ByID(261520641);
}

// Private type creation functions
const $$createType0 = stores$0.Node.createFrom;
const $$createType1 = stores$0.NodeInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
