// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TriggersService manages trigger registration and execution
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as trigger$0 from "../internal/trigger/models.js";

/**
 * ExecuteCommand executes a command trigger (for command-based triggers)
 */
export function ExecuteCommand(command: string, args: { [_: string]: any }): $CancellablePromise<void> {
    return $Call.ByID(1934206283, command, args);
}

/**
 * GetActiveTriggers returns all active triggers
 */
export function GetActiveTriggers(): $CancellablePromise<(trigger$0.Instance | null)[]> {
    return $Call.ByID(2616387194).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * GetRegisteredCommands returns all registered commands
 */
export function GetRegisteredCommands(): $CancellablePromise<string[]> {
    return $Call.ByID(98938427).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetSupportedNodeRefs returns all supported node references from the registry
 */
export function GetSupportedNodeRefs(): $CancellablePromise<string[]> {
    return $Call.ByID(474231515).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetTriggerStats returns trigger statistics
 */
export function GetTriggerStats(): $CancellablePromise<{ [_: string]: any }> {
    return $Call.ByID(2836942842).then(($result: any) => {
        return $$createType4($result);
    });
}

/**
 * GetTriggersByRecipe returns triggers for a specific recipe
 */
export function GetTriggersByRecipe(recipeID: string): $CancellablePromise<(trigger$0.Instance | null)[]> {
    return $Call.ByID(2764122355, recipeID).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * RefreshAllTriggers refreshes all triggers (useful for bulk updates)
 */
export function RefreshAllTriggers(): $CancellablePromise<void> {
    return $Call.ByID(804027148);
}

/**
 * RefreshRecipeTriggers refreshes triggers for a specific recipe (call after recipe updates).
 */
export function RefreshRecipeTriggers(recipeID: string): $CancellablePromise<void> {
    return $Call.ByID(3196380101, recipeID);
}

/**
 * RegisterHandler dynamically registers a handler instance
 */
export function RegisterHandler(handler: trigger$0.Handler): $CancellablePromise<void> {
    return $Call.ByID(149706930, handler);
}

/**
 * RegisterRecipe registers triggers for a recipe
 */
export function RegisterRecipe(recipeID: string): $CancellablePromise<void> {
    return $Call.ByID(365997560, recipeID);
}

/**
 * Start starts the triggers service and registers all existing recipe triggers.
 */
export function Start(): $CancellablePromise<void> {
    return $Call.ByID(3718432365);
}

/**
 * UnregisterHandler dynamically unregisters a trigger handler
 */
export function UnregisterHandler(nodeRef: string): $CancellablePromise<void> {
    return $Call.ByID(2711613639, nodeRef);
}

/**
 * UnregisterRecipe unregisters triggers for a recipe
 */
export function UnregisterRecipe(recipeID: string): $CancellablePromise<void> {
    return $Call.ByID(278580603, recipeID);
}

// Private type creation functions
const $$createType0 = trigger$0.Instance.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $Create.Map($Create.Any, $Create.Any);
