// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Instance represents an active trigger instance
 */
export class Instance {
    "id": string;
    "recipeId": string;
    "nodeId": string;
    "type": TriggerType;
    "config": { [_: string]: any };
    "status": Status;
    "createdAt": time$0.Time;
    "updatedAt": time$0.Time;

    /**
     * Runtime statistics (memory only)
     */
    "triggerCount": number;
    "lastTriggered"?: time$0.Time | null;
    "lastError"?: string;

    /** Creates a new Instance instance. */
    constructor($$source: Partial<Instance> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("recipeId" in $$source)) {
            this["recipeId"] = "";
        }
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = TriggerType.$zero;
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("triggerCount" in $$source)) {
            this["triggerCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Instance instance from a string or object.
     */
    static createFrom($$source: any = {}): Instance {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField4_0($$parsedSource["config"]);
        }
        return new Instance($$parsedSource as Partial<Instance>);
    }
}

export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StatusActive = "active",
    StatusInactive = "inactive",
    StatusError = "error",
};

export enum TriggerType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TypeWebhook = "webhook",
    TypeSchedule = "schedule",
    TypeCommand = "command",
    TypeFileWatch = "filewatch",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
