// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * Handler defines the interface that all trigger handlers must implement.
 * Handlers are responsible for managing specific types of triggers.
 */
export type Handler = any;

/**
 * Instance represents an active trigger instance with configuration and runtime data.
 */
export class Instance {
    /**
     * Unique instance identifier
     */
    "id": string;

    /**
     * Associated recipe ID
     */
    "recipeId": string;

    /**
     * Source node ID in recipe
     */
    "nodeId": string;

    /**
     * Node reference
     */
    "nodeRef": string;

    /**
     * Trigger configuration
     */
    "config": { [_: string]: any };

    /**
     * Current status
     */
    "status": Status;

    /**
     * Creation timestamp
     */
    "createdAt": time$0.Time;

    /**
     * Last update timestamp
     */
    "updatedAt": time$0.Time;

    /**
     * Runtime statistics (memory only)
     * Total trigger executions
     */
    "triggerCount": number;

    /**
     * Last execution time
     */
    "lastTriggered"?: time$0.Time | null;

    /**
     * Last error message
     */
    "lastError"?: string;

    /** Creates a new Instance instance. */
    constructor($$source: Partial<Instance> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("recipeId" in $$source)) {
            this["recipeId"] = "";
        }
        if (!("nodeId" in $$source)) {
            this["nodeId"] = "";
        }
        if (!("nodeRef" in $$source)) {
            this["nodeRef"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }
        if (!("status" in $$source)) {
            this["status"] = Status.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            this["updatedAt"] = null;
        }
        if (!("triggerCount" in $$source)) {
            this["triggerCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Instance instance from a string or object.
     */
    static createFrom($$source: any = {}): Instance {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField4_0($$parsedSource["config"]);
        }
        return new Instance($$parsedSource as Partial<Instance>);
    }
}

/**
 * Status represents the current state of a trigger instance.
 */
export enum Status {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * Trigger instance states.
     *
     * Trigger is active and monitoring
     */
    StatusActive = "active",

    /**
     * Trigger is disabled
     */
    StatusInactive = "inactive",

    /**
     * Trigger encountered an error
     */
    StatusError = "error",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
