// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as node$0 from "../node/models.js";

/**
 * FlowEdge represents a connection between two nodes in the workflow.
 * It defines the data flow from source node to target node through specific handles.
 */
export class FlowEdge {
    "id": string;
    "source": string;
    "target": string;

    /**
     * Output handle ID from source node
     */
    "sourceHandle": string;

    /**
     * Input handle ID to target node (optional)
     */
    "targetHandle": string;
    "type"?: string;

    /** Creates a new FlowEdge instance. */
    constructor($$source: Partial<FlowEdge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }
        if (!("sourceHandle" in $$source)) {
            this["sourceHandle"] = "";
        }
        if (!("targetHandle" in $$source)) {
            this["targetHandle"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlowEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): FlowEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlowEdge($$parsedSource as Partial<FlowEdge>);
    }
}

/**
 * Node represents a workflow node instance with position and runtime data.
 * It combines NodeData with instance-specific information like ID and position.
 */
export class Node {
    "id": string;
    "type": string;
    "position": Position;
    "data": NodeData;

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("position" in $$source)) {
            this["position"] = null;
        }
        if (!("data" in $$source)) {
            this["data"] = (new NodeData());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField3_0($$parsedSource["data"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

/**
 * NodeData contains the metadata and configuration for a workflow node.
 * It includes all the information needed to display and execute the node.
 */
export class NodeData {
    "ref": string;
    "icon": string;
    "label": string;
    "name": string;
    "nodeType": string;
    "description": string;
    "properties": node$0.NodeProperty[];
    "outputs": node$0.NodeProperty[];
    "outputHandles": node$0.OutputHandle[];

    /** Creates a new NodeData instance. */
    constructor($$source: Partial<NodeData> = {}) {
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("nodeType" in $$source)) {
            this["nodeType"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("properties" in $$source)) {
            this["properties"] = [];
        }
        if (!("outputs" in $$source)) {
            this["outputs"] = [];
        }
        if (!("outputHandles" in $$source)) {
            this["outputHandles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeData instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeData {
        const $$createField6_0 = $$createType2;
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField6_0($$parsedSource["properties"]);
        }
        if ("outputs" in $$parsedSource) {
            $$parsedSource["outputs"] = $$createField7_0($$parsedSource["outputs"]);
        }
        if ("outputHandles" in $$parsedSource) {
            $$parsedSource["outputHandles"] = $$createField8_0($$parsedSource["outputHandles"]);
        }
        return new NodeData($$parsedSource as Partial<NodeData>);
    }
}

/**
 * Position represents a 2D coordinate as [x, y] array.
 * It supports both YAML array format [x,y] and JSON object format {"x":x,"y":y}.
 */
export type Position = any;

/**
 * Recipe represents a complete workflow definition with nodes and connections.
 * It contains all the information needed to execute a workflow.
 */
export class Recipe {
    "name": string;
    "path": string;
    "description": string;
    "nodes": Node[];
    "edges": FlowEdge[];

    /** Creates a new Recipe instance. */
    constructor($$source: Partial<Recipe> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recipe instance from a string or object.
     */
    static createFrom($$source: any = {}): Recipe {
        const $$createField3_0 = $$createType6;
        const $$createField4_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField4_0($$parsedSource["edges"]);
        }
        return new Recipe($$parsedSource as Partial<Recipe>);
    }
}

// Private type creation functions
const $$createType0 = NodeData.createFrom;
const $$createType1 = node$0.NodeProperty.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = node$0.OutputHandle.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = Node.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = FlowEdge.createFrom;
const $$createType8 = $Create.Array($$createType7);
