// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as node$0 from "../node/models.js";

/**
 * FlowEdge represents a connection between nodes
 */
export class FlowEdge {
    "id": string;
    "source": string;
    "target": string;
    "type"?: string;

    /** Creates a new FlowEdge instance. */
    constructor($$source: Partial<FlowEdge> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("target" in $$source)) {
            this["target"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlowEdge instance from a string or object.
     */
    static createFrom($$source: any = {}): FlowEdge {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlowEdge($$parsedSource as Partial<FlowEdge>);
    }
}

export class Node {
    "id": string;
    "ref": string;
    "name": string;
    "description": string;
    "type": string;
    "pos": Position;
    "properties": node$0.NodeProperty[];
    "output": node$0.NodeProperty[];

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("pos" in $$source)) {
            this["pos"] = Array.from({ length: 2 }, () => 0);
        }
        if (!("properties" in $$source)) {
            this["properties"] = [];
        }
        if (!("output" in $$source)) {
            this["output"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("properties" in $$parsedSource) {
            $$parsedSource["properties"] = $$createField6_0($$parsedSource["properties"]);
        }
        if ("output" in $$parsedSource) {
            $$parsedSource["output"] = $$createField7_0($$parsedSource["output"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

export type Position = number[];

export class Recipe {
    "name": string;
    "path": string;
    "description": string;
    "nodes": Node[];
    "edges": FlowEdge[];

    /** Creates a new Recipe instance. */
    constructor($$source: Partial<Recipe> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("edges" in $$source)) {
            this["edges"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Recipe instance from a string or object.
     */
    static createFrom($$source: any = {}): Recipe {
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        if ("edges" in $$parsedSource) {
            $$parsedSource["edges"] = $$createField4_0($$parsedSource["edges"]);
        }
        return new Recipe($$parsedSource as Partial<Recipe>);
    }
}

// Private type creation functions
const $$createType0 = node$0.NodeProperty.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = Node.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = FlowEdge.createFrom;
const $$createType5 = $Create.Array($$createType4);
