// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: credentials.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const checkCredentialNameExists = `-- name: CheckCredentialNameExists :one
SELECT COUNT(*) as count FROM credentials
WHERE name = ?
`

func (q *Queries) CheckCredentialNameExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCredentialNameExists, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id, name, type, description, keychain_key, 
    encrypted_data, salt, storage_type
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at
`

type CreateCredentialParams struct {
	ID            string
	Name          string
	Type          string
	Description   sql.NullString
	KeychainKey   sql.NullString
	EncryptedData []byte
	Salt          []byte
	StorageType   string
}

func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.KeychainKey,
		arg.EncryptedData,
		arg.Salt,
		arg.StorageType,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials
WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, id)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at FROM credentials
WHERE id = ? LIMIT 1
`

func (q *Queries) GetCredential(ctx context.Context, id string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCredentialByName = `-- name: GetCredentialByName :one
SELECT id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at FROM credentials
WHERE name = ? LIMIT 1
`

func (q *Queries) GetCredentialByName(ctx context.Context, name string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByName, name)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCredentialForUse = `-- name: GetCredentialForUse :one
SELECT id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at FROM credentials
WHERE name = ?
LIMIT 1
`

func (q *Queries) GetCredentialForUse(ctx context.Context, name string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialForUse, name)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getUnusedCredentials = `-- name: GetUnusedCredentials :many
SELECT 
    id, name, type, description, storage_type, 
    created_at, updated_at, last_used_at
FROM credentials
WHERE last_used_at IS NULL 
   OR last_used_at < datetime('now', '-90 days')
ORDER BY last_used_at ASC NULLS FIRST
`

type GetUnusedCredentialsRow struct {
	ID          string
	Name        string
	Type        string
	Description sql.NullString
	StorageType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastUsedAt  sql.NullTime
}

func (q *Queries) GetUnusedCredentials(ctx context.Context) ([]GetUnusedCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnusedCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnusedCredentialsRow
	for rows.Next() {
		var i GetUnusedCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT 
    id, name, type, description, storage_type, 
    created_at, updated_at, last_used_at
FROM credentials
ORDER BY name ASC
`

type ListCredentialsRow struct {
	ID          string
	Name        string
	Type        string
	Description sql.NullString
	StorageType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastUsedAt  sql.NullTime
}

func (q *Queries) ListCredentials(ctx context.Context) ([]ListCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsRow
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentialsByType = `-- name: ListCredentialsByType :many
SELECT 
    id, name, type, description, storage_type, 
    created_at, updated_at, last_used_at
FROM credentials
WHERE type = ?
ORDER BY name ASC
`

type ListCredentialsByTypeRow struct {
	ID          string
	Name        string
	Type        string
	Description sql.NullString
	StorageType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastUsedAt  sql.NullTime
}

func (q *Queries) ListCredentialsByType(ctx context.Context, type_ string) ([]ListCredentialsByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listCredentialsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsByTypeRow
	for rows.Next() {
		var i ListCredentialsByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCredentialsByName = `-- name: SearchCredentialsByName :many
SELECT 
    id, name, type, description, storage_type, 
    created_at, updated_at, last_used_at
FROM credentials
WHERE name LIKE ?
ORDER BY name ASC
`

type SearchCredentialsByNameRow struct {
	ID          string
	Name        string
	Type        string
	Description sql.NullString
	StorageType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastUsedAt  sql.NullTime
}

func (q *Queries) SearchCredentialsByName(ctx context.Context, name string) ([]SearchCredentialsByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchCredentialsByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCredentialsByNameRow
	for rows.Next() {
		var i SearchCredentialsByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :one
UPDATE credentials
SET 
    name = ?,
    type = ?,
    description = ?,
    keychain_key = ?,
    encrypted_data = ?,
    salt = ?,
    storage_type = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at
`

type UpdateCredentialParams struct {
	Name          string
	Type          string
	Description   sql.NullString
	KeychainKey   sql.NullString
	EncryptedData []byte
	Salt          []byte
	StorageType   string
	ID            string
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, updateCredential,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.KeychainKey,
		arg.EncryptedData,
		arg.Salt,
		arg.StorageType,
		arg.ID,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateCredentialLastUsed = `-- name: UpdateCredentialLastUsed :exec
UPDATE credentials
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateCredentialLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateCredentialLastUsed, id)
	return err
}
