// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Credential struct {
	ID            string
	Name          string
	Type          string
	Description   sql.NullString
	KeychainKey   sql.NullString
	EncryptedData []byte
	Salt          []byte
	StorageType   string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LastUsedAt    sql.NullTime
}

type Execution struct {
	ID               string
	RecipeID         string
	Foreign          interface{}
	Status           string
	StartedAt        time.Time
	FinishedAt       sql.NullTime
	DurationMs       sql.NullInt64
	ErrorMessage     sql.NullString
	InputData        sql.NullString
	OutputData       sql.NullString
	ExecutionContext sql.NullString
}

type Recipe struct {
	ID          string
	Name        string
	Description sql.NullString
	RecipePath  string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
