// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const checkCredentialExists = `-- name: CheckCredentialExists :one
SELECT COUNT(*) FROM credentials WHERE name = ?
`

func (q *Queries) CheckCredentialExists(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkCredentialExists, name)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExecutionsByStatus = `-- name: CountExecutionsByStatus :one
SELECT COUNT(*) FROM executions WHERE status = ?
`

func (q *Queries) CountExecutionsByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countExecutionsByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredential = `-- name: CreateCredential :one
INSERT INTO credentials (
    id, name, type, description, keychain_key, encrypted_data, salt, storage_type
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
) RETURNING id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at
`

type CreateCredentialParams struct {
	ID            string
	Name          string
	Type          string
	Description   sql.NullString
	KeychainKey   sql.NullString
	EncryptedData []byte
	Salt          []byte
	StorageType   string
}

// Credentials queries
func (q *Queries) CreateCredential(ctx context.Context, arg CreateCredentialParams) (Credential, error) {
	row := q.db.QueryRowContext(ctx, createCredential,
		arg.ID,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.KeychainKey,
		arg.EncryptedData,
		arg.Salt,
		arg.StorageType,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (
    id, workflow_path, workflow_name, status, started_at, input_data, execution_context
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
) RETURNING id, workflow_path, workflow_name, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context
`

type CreateExecutionParams struct {
	ID               string
	WorkflowPath     string
	WorkflowName     string
	Status           string
	StartedAt        time.Time
	InputData        sql.NullString
	ExecutionContext sql.NullString
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRowContext(ctx, createExecution,
		arg.ID,
		arg.WorkflowPath,
		arg.WorkflowName,
		arg.Status,
		arg.StartedAt,
		arg.InputData,
		arg.ExecutionContext,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowPath,
		&i.WorkflowName,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.InputData,
		&i.OutputData,
		&i.ExecutionContext,
	)
	return i, err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM credentials WHERE id = ?
`

func (q *Queries) DeleteCredential(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, id)
	return err
}

const deleteExecution = `-- name: DeleteExecution :exec
DELETE FROM executions WHERE id = ?
`

func (q *Queries) DeleteExecution(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteExecution, id)
	return err
}

const deleteOldExecutions = `-- name: DeleteOldExecutions :exec
DELETE FROM executions 
WHERE started_at < datetime('now', '-' || ? || ' days')
`

func (q *Queries) DeleteOldExecutions(ctx context.Context, dollar_1 sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteOldExecutions, dollar_1)
	return err
}

const getCredential = `-- name: GetCredential :one
SELECT id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at FROM credentials WHERE id = ?
`

func (q *Queries) GetCredential(ctx context.Context, id string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredential, id)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCredentialByName = `-- name: GetCredentialByName :one
SELECT id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at FROM credentials WHERE name = ?
`

func (q *Queries) GetCredentialByName(ctx context.Context, name string) (Credential, error) {
	row := q.db.QueryRowContext(ctx, getCredentialByName, name)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.KeychainKey,
		&i.EncryptedData,
		&i.Salt,
		&i.StorageType,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getCredentialsByStorageType = `-- name: GetCredentialsByStorageType :many
SELECT id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at FROM credentials 
WHERE storage_type = ?
ORDER BY name
`

func (q *Queries) GetCredentialsByStorageType(ctx context.Context, storageType string) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialsByStorageType, storageType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.KeychainKey,
			&i.EncryptedData,
			&i.Salt,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCredentialsByType = `-- name: GetCredentialsByType :many
SELECT id, name, type, description, keychain_key, encrypted_data, salt, storage_type, created_at, updated_at, last_used_at FROM credentials 
WHERE type = ?
ORDER BY name
`

func (q *Queries) GetCredentialsByType(ctx context.Context, type_ string) ([]Credential, error) {
	rows, err := q.db.QueryContext(ctx, getCredentialsByType, type_)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Credential
	for rows.Next() {
		var i Credential
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.KeychainKey,
			&i.EncryptedData,
			&i.Salt,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecution = `-- name: GetExecution :one
SELECT id, workflow_path, workflow_name, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions WHERE id = ?
`

func (q *Queries) GetExecution(ctx context.Context, id string) (Execution, error) {
	row := q.db.QueryRowContext(ctx, getExecution, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.WorkflowPath,
		&i.WorkflowName,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.InputData,
		&i.OutputData,
		&i.ExecutionContext,
	)
	return i, err
}

const getExecutionStats = `-- name: GetExecutionStats :one
SELECT 
    COUNT(*) as total_count,
    COUNT(CASE WHEN status = 'success' THEN 1 END) as success_count,
    COUNT(CASE WHEN status = 'failed' THEN 1 END) as failed_count,
    COUNT(CASE WHEN status = 'running' THEN 1 END) as running_count,
    AVG(CASE WHEN duration_ms IS NOT NULL THEN duration_ms END) as avg_duration_ms
FROM executions
WHERE workflow_path = ?
`

type GetExecutionStatsRow struct {
	TotalCount    int64
	SuccessCount  int64
	FailedCount   int64
	RunningCount  int64
	AvgDurationMs sql.NullFloat64
}

func (q *Queries) GetExecutionStats(ctx context.Context, workflowPath string) (GetExecutionStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getExecutionStats, workflowPath)
	var i GetExecutionStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.SuccessCount,
		&i.FailedCount,
		&i.RunningCount,
		&i.AvgDurationMs,
	)
	return i, err
}

const getExecutionsByStatus = `-- name: GetExecutionsByStatus :many
SELECT id, workflow_path, workflow_name, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions 
WHERE status = ?
ORDER BY started_at DESC
LIMIT ?
`

type GetExecutionsByStatusParams struct {
	Status string
	Limit  int64
}

func (q *Queries) GetExecutionsByStatus(ctx context.Context, arg GetExecutionsByStatusParams) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowPath,
			&i.WorkflowName,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionsByWorkflow = `-- name: GetExecutionsByWorkflow :many
SELECT id, workflow_path, workflow_name, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions 
WHERE workflow_path = ?
ORDER BY started_at DESC
LIMIT ?
`

type GetExecutionsByWorkflowParams struct {
	WorkflowPath string
	Limit        int64
}

func (q *Queries) GetExecutionsByWorkflow(ctx context.Context, arg GetExecutionsByWorkflowParams) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getExecutionsByWorkflow, arg.WorkflowPath, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowPath,
			&i.WorkflowName,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentExecutions = `-- name: GetRecentExecutions :many
SELECT id, workflow_path, workflow_name, status, started_at, finished_at, duration_ms, error_message, input_data, output_data, execution_context FROM executions 
ORDER BY started_at DESC 
LIMIT ?
`

func (q *Queries) GetRecentExecutions(ctx context.Context, limit int64) ([]Execution, error) {
	rows, err := q.db.QueryContext(ctx, getRecentExecutions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Execution
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowPath,
			&i.WorkflowName,
			&i.Status,
			&i.StartedAt,
			&i.FinishedAt,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.InputData,
			&i.OutputData,
			&i.ExecutionContext,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCredentials = `-- name: ListCredentials :many
SELECT id, name, type, description, storage_type, created_at, updated_at, last_used_at 
FROM credentials
ORDER BY name
`

type ListCredentialsRow struct {
	ID          string
	Name        string
	Type        string
	Description sql.NullString
	StorageType string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	LastUsedAt  sql.NullTime
}

func (q *Queries) ListCredentials(ctx context.Context) ([]ListCredentialsRow, error) {
	rows, err := q.db.QueryContext(ctx, listCredentials)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCredentialsRow
	for rows.Next() {
		var i ListCredentialsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.StorageType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCredential = `-- name: UpdateCredential :exec
UPDATE credentials 
SET type = ?, description = ?, keychain_key = ?, encrypted_data = ?, salt = ?, storage_type = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateCredentialParams struct {
	Type          string
	Description   sql.NullString
	KeychainKey   sql.NullString
	EncryptedData []byte
	Salt          []byte
	StorageType   string
	ID            string
}

func (q *Queries) UpdateCredential(ctx context.Context, arg UpdateCredentialParams) error {
	_, err := q.db.ExecContext(ctx, updateCredential,
		arg.Type,
		arg.Description,
		arg.KeychainKey,
		arg.EncryptedData,
		arg.Salt,
		arg.StorageType,
		arg.ID,
	)
	return err
}

const updateCredentialLastUsed = `-- name: UpdateCredentialLastUsed :exec
UPDATE credentials 
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateCredentialLastUsed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateCredentialLastUsed, id)
	return err
}

const updateExecutionError = `-- name: UpdateExecutionError :exec
UPDATE executions 
SET status = 'failed', finished_at = CURRENT_TIMESTAMP, duration_ms = ?, error_message = ?
WHERE id = ?
`

type UpdateExecutionErrorParams struct {
	DurationMs   sql.NullInt64
	ErrorMessage sql.NullString
	ID           string
}

func (q *Queries) UpdateExecutionError(ctx context.Context, arg UpdateExecutionErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateExecutionError, arg.DurationMs, arg.ErrorMessage, arg.ID)
	return err
}

const updateExecutionFinished = `-- name: UpdateExecutionFinished :exec
UPDATE executions 
SET status = ?, finished_at = CURRENT_TIMESTAMP, duration_ms = ?, output_data = ?
WHERE id = ?
`

type UpdateExecutionFinishedParams struct {
	Status     string
	DurationMs sql.NullInt64
	OutputData sql.NullString
	ID         string
}

func (q *Queries) UpdateExecutionFinished(ctx context.Context, arg UpdateExecutionFinishedParams) error {
	_, err := q.db.ExecContext(ctx, updateExecutionFinished,
		arg.Status,
		arg.DurationMs,
		arg.OutputData,
		arg.ID,
	)
	return err
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :exec
UPDATE executions 
SET status = ?, finished_at = ?, duration_ms = ?, error_message = ?, output_data = ?
WHERE id = ?
`

type UpdateExecutionStatusParams struct {
	Status       string
	FinishedAt   sql.NullTime
	DurationMs   sql.NullInt64
	ErrorMessage sql.NullString
	OutputData   sql.NullString
	ID           string
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateExecutionStatus,
		arg.Status,
		arg.FinishedAt,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.OutputData,
		arg.ID,
	)
	return err
}
