// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: recipes.sql

package database

import (
	"context"
	"database/sql"
)

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
    id, name, description, recipe_path
) VALUES (
    ?, ?, ?, ?
)
RETURNING id, name, description, recipe_path, created_at, updated_at
`

type CreateRecipeParams struct {
	ID          string
	Name        string
	Description sql.NullString
	RecipePath  string
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, createRecipe,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.RecipePath,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE id = ?
`

func (q *Queries) DeleteRecipe(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRecipe, id)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, name, description, recipe_path, created_at, updated_at FROM recipes
WHERE id = ? LIMIT 1
`

func (q *Queries) GetRecipe(ctx context.Context, id string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeByPath = `-- name: GetRecipeByPath :one
SELECT id, name, description, recipe_path, created_at, updated_at FROM recipes
WHERE recipe_path = ?
LIMIT 1
`

func (q *Queries) GetRecipeByPath(ctx context.Context, recipePath string) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, getRecipeByPath, recipePath)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecipes = `-- name: ListRecipes :many
SELECT id, name, description, recipe_path, created_at, updated_at FROM recipes
ORDER BY created_at DESC
`

func (q *Queries) ListRecipes(ctx context.Context) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, listRecipes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RecipePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipesByName = `-- name: SearchRecipesByName :many
SELECT id, name, description, recipe_path, created_at, updated_at FROM recipes
WHERE name LIKE ?
ORDER BY created_at DESC
`

func (q *Queries) SearchRecipesByName(ctx context.Context, name string) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, searchRecipesByName, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.RecipePath,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET 
    name = ?,
    description = ?,
    recipe_path = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
RETURNING id, name, description, recipe_path, created_at, updated_at
`

type UpdateRecipeParams struct {
	Name        string
	Description sql.NullString
	RecipePath  string
	ID          string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, updateRecipe,
		arg.Name,
		arg.Description,
		arg.RecipePath,
		arg.ID,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.RecipePath,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
