// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * InputConfig defines the configuration for input UI
 */
export class InputConfig {
    "type": InputType;

    /**
     * For range and number inputs
     */
    "min"?: number | null;

    /**
     * For range and number inputs
     */
    "max"?: number | null;

    /**
     * For range and number inputs
     */
    "step"?: number | null;

    /**
     * For text and textarea inputs
     */
    "placeholder"?: string;

    /**
     * For textarea input
     */
    "rows"?: number;

    /**
     * For select inputs
     */
    "multiple"?: boolean;

    /**
     * For dynamic list inputs - ensure unique elements
     */
    "unique"?: boolean;

    /** Creates a new InputConfig instance. */
    constructor($$source: Partial<InputConfig> = {}) {
        if (!("type" in $$source)) {
            this["type"] = InputType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new InputConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): InputConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new InputConfig($$parsedSource as Partial<InputConfig>);
    }
}

/**
 * InputType defines how the property should be displayed in the UI
 */
export enum InputType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * Single line text input
     */
    InputTypeText = 1,

    /**
     * Multi-line text input
     */
    InputTypeTextarea = 2,

    /**
     * Number input
     */
    InputTypeNumber = 3,

    /**
     * Slider input
     */
    InputTypeRange = 4,

    /**
     * Dropdown select
     */
    InputTypeSelect = 5,

    /**
     * Multiple selection
     */
    InputTypeMultiSelect = 6,

    /**
     * Toggle switch
     */
    InputTypeSwitch = 7,

    /**
     * Checkbox
     */
    InputTypeCheckbox = 8,

    /**
     * Expression input
     */
    InputTypeExpression = 9,

    /**
     * Key-value pairs input
     */
    InputTypeKeyValue = 10,

    /**
     * Dynamic list input
     */
    InputTypeDynamicList = 11,
};

/**
 * NodeInfo contains metadata about a workflow node.
 */
export class NodeInfo {
    /**
     * Unique identifier for the node type
     */
    "ref": string;

    /**
     * Human-readable name
     */
    "name": string;

    /**
     * Brief description of node functionality
     */
    "description": string;

    /**
     * Category of the node
     */
    "type": NodeType;

    /**
     * Icon name (Lucide icon set)
     */
    "icon": string;

    /** Creates a new NodeInfo instance. */
    constructor($$source: Partial<NodeInfo> = {}) {
        if (!("ref" in $$source)) {
            this["ref"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = NodeType.$zero;
        }
        if (!("icon" in $$source)) {
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeInfo($$parsedSource as Partial<NodeInfo>);
    }
}

export class NodeProperty {
    /**
     * Type of the property (string, number, boolean, array, json, xml)
     */
    "type": PropertyType;

    /**
     * Input configuration for UI
     */
    "input"?: InputConfig | null;

    /**
     * Name of the property
     */
    "name": string;

    /**
     * Description of the property
     */
    "description": string;

    /**
     * Whether the property is required
     */
    "optional": boolean;

    /**
     * Key of the property
     */
    "key": string;

    /**
     * Value of the property
     */
    "value": any;

    /**
     * Options of the property (for select/multi-select)
     */
    "options": string[];

    /**
     * not editable
     */
    "readOnly": boolean;

    /** Creates a new NodeProperty instance. */
    constructor($$source: Partial<NodeProperty> = {}) {
        if (!("type" in $$source)) {
            this["type"] = PropertyType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("optional" in $$source)) {
            this["optional"] = false;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeProperty instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeProperty {
        const $$createField1_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("input" in $$parsedSource) {
            $$parsedSource["input"] = $$createField1_0($$parsedSource["input"]);
        }
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField7_0($$parsedSource["options"]);
        }
        return new NodeProperty($$parsedSource as Partial<NodeProperty>);
    }
}

/**
 * NodeType represents the category of a workflow node.
 */
export enum NodeType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * NodeTypeTrigger initiates workflow execution
     */
    NodeTypeTrigger = "trigger",

    /**
     * NodeTypeBranch controls workflow flow logic
     */
    NodeTypeBranch = "branch",

    /**
     * NodeTypeAction performs operations or side effects
     */
    NodeTypeAction = "action",

    /**
     * NodeTypeUtil provides utility functions
     */
    NodeTypeUtil = "util",
};

/**
 * OutputHandle represents a connection point from a node.
 * Nodes can have multiple output handles for different execution paths.
 */
export class OutputHandle {
    /**
     * Unique identifier for this handle
     */
    "id": string;

    /**
     * Optional human-readable label
     */
    "label"?: string;

    /**
     * Optional description of when this handle is used
     */
    "description"?: string;

    /** Creates a new OutputHandle instance. */
    constructor($$source: Partial<OutputHandle> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OutputHandle instance from a string or object.
     */
    static createFrom($$source: any = {}): OutputHandle {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OutputHandle($$parsedSource as Partial<OutputHandle>);
    }
}

export enum PropertyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * Basic Types
     */
    Invalid = 0,
    Bool = 1,
    Int64 = 2,
    Uint64 = 3,
    Float64 = 4,
    String = 5,

    /**
     * Special Types
     */
    $JSON = 6,
    XML = 7,
    Date = 8,

    /**
     * Arrays
     */
    StringArray = 9,
    NumberArray = 10,
    BooleanArray = 11,
};

// Private type creation functions
const $$createType0 = InputConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
