package branch

import (
	"github.com/ironpark/teatime/internal/node"
)

func init() {
	node.RegisterNode(&FilterBranchNode{
		BaseNode: node.NewBaseNode(
			"teatime.branch.filter",
			node.NodeTypeBranch,
			"Filter",
			"데이터를 필터링하여 조건에 맞는 항목만 처리하는 필터 브랜치 노드입니다.",
			"ListFilter",
			[]node.NodeProperty{
				node.JSONProp("inputData", "Input Data",
					node.WithDescription("필터링할 입력 데이터 (배열)"),
					node.RequiredWithDefault("[]"),
				),
				node.SelectProp("filterType", "Filter Type", []string{"simple", "complex", "custom", "regex", "range", "unique", "duplicate"},
					node.WithDescription("필터 타입"),
					node.RequiredWithDefault("simple"),
				),
				node.StringProp("filterField", "Filter Field",
					node.WithDescription("필터링할 필드명 (객체 배열의 경우)"),
					node.Optional(),
				),
				node.SelectProp("filterOperator", "Filter Operator", []string{"==", "!=", ">", "<", ">=", "<=", "contains", "notContains", "startsWith", "endsWith", "in", "notIn", "between", "isNull", "isNotNull"},
					node.WithDescription("필터 연산자"),
					node.OptionalWithDefault("=="),
				),
				node.StringProp("filterValue", "Filter Value",
					node.WithDescription("필터 값"),
					node.Optional(),
				),
				node.StringProp("filterExpression", "Filter Expression",
					node.WithDescription("복잡한 필터 표현식 (custom 타입용)"),
					node.Optional(),
				),
				node.JSONProp("multipleFilters", "Multiple Filters",
					node.WithDescription("다중 필터 조건 (JSON 배열)"),
					node.OptionalWithDefault("[]"),
				),
				node.SelectProp("filterLogic", "Filter Logic", []string{"AND", "OR", "XOR", "CUSTOM"},
					node.WithDescription("다중 필터 논리 연산"),
					node.OptionalWithDefault("AND"),
				),
				node.BoolProp("caseSensitive", "Case Sensitive",
					node.WithDescription("대소문자 구분"),
					node.OptionalWithDefault(true),
				),
				node.SelectProp("nullHandling", "Null Handling", []string{"include", "exclude", "only"},
					node.WithDescription("NULL 값 처리 방식"),
					node.OptionalWithDefault("exclude"),
				),
				node.BoolProp("sortAfterFilter", "Sort After Filter",
					node.WithDescription("필터링 후 정렬 여부"),
					node.OptionalWithDefault(false),
				),
				node.StringProp("sortField", "Sort Field",
					node.WithDescription("정렬 필드"),
					node.Optional(),
				),
				node.SelectProp("sortOrder", "Sort Order", []string{"asc", "desc"},
					node.WithDescription("정렬 순서"),
					node.OptionalWithDefault("asc"),
				),
				node.IntProp("limit", "Limit",
					node.WithDescription("결과 제한 수"),
					node.OptionalWithDefault(int64(0)),
				),
				node.IntProp("offset", "Offset",
					node.WithDescription("시작 오프셋"),
					node.OptionalWithDefault(int64(0)),
				),
			},
			[]node.NodeProperty{
				node.OutputProp(node.StringArray, "filteredItems", "Filtered Items",
					node.WithDescription("필터링된 항목들"),
				),
				node.OutputProp(node.StringArray, "rejectedItems", "Rejected Items",
					node.WithDescription("필터링에서 제외된 항목들"),
				),
				node.OutputProp(node.Int64, "filteredCount", "Filtered Count",
					node.WithDescription("필터링된 항목 수"),
				),
				node.OutputProp(node.Int64, "rejectedCount", "Rejected Count",
					node.WithDescription("제외된 항목 수"),
				),
				node.OutputProp(node.Int64, "totalCount", "Total Count",
					node.WithDescription("전체 항목 수"),
				),
				node.OutputProp(node.Float64, "filterRate", "Filter Rate",
					node.WithDescription("필터링 비율 (%)"),
				),
			},
			nil, // Use default output handle
		),
	})
}

// 데이터를 필터링하여 분기 처리하는 필터 브랜치 노드
type FilterBranchNode struct {
	node.BaseNode
}
