// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as types$0 from "../node/types/models.js";

export class Node {
    "Id": string;
    "LocalId": string;
    "Name": string;
    "Description": string;
    "Type": string;
    "Properties": types$0.NodeProperty[];
    "Output": types$0.NodeProperty[];

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("LocalId" in $$source)) {
            this["LocalId"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Properties" in $$source)) {
            this["Properties"] = [];
        }
        if (!("Output" in $$source)) {
            this["Output"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Properties" in $$parsedSource) {
            $$parsedSource["Properties"] = $$createField5_0($$parsedSource["Properties"]);
        }
        if ("Output" in $$parsedSource) {
            $$parsedSource["Output"] = $$createField6_0($$parsedSource["Output"]);
        }
        return new Node($$parsedSource as Partial<Node>);
    }
}

export class NodeInfo {
    "Id": string;
    "Name": string;
    "Type": string;
    "Description": string;

    /** Creates a new NodeInfo instance. */
    constructor($$source: Partial<NodeInfo> = {}) {
        if (!("Id" in $$source)) {
            this["Id"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Type" in $$source)) {
            this["Type"] = "";
        }
        if (!("Description" in $$source)) {
            this["Description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NodeInfo($$parsedSource as Partial<NodeInfo>);
    }
}

// Private type creation functions
const $$createType0 = types$0.NodeProperty.createFrom;
const $$createType1 = $Create.Array($$createType0);
