// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class NodeProperty {
    /**
     * Type of the property (string, number, boolean, array, json, xml)
     */
    "type": PropertyType;

    /**
     * Name of the property
     */
    "name": string;

    /**
     * Description of the property
     */
    "description": string;

    /**
     * Whether the property is required
     */
    "optional": boolean;

    /**
     * Key of the property
     */
    "key": string;

    /**
     * Value of the property
     */
    "value": string;

    /**
     * Options of the property
     */
    "options": string[];

    /**
     * not editable
     */
    "readOnly": boolean;

    /** Creates a new NodeProperty instance. */
    constructor($$source: Partial<NodeProperty> = {}) {
        if (!("type" in $$source)) {
            this["type"] = PropertyType.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }
        if (!("optional" in $$source)) {
            this["optional"] = false;
        }
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("options" in $$source)) {
            this["options"] = [];
        }
        if (!("readOnly" in $$source)) {
            this["readOnly"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeProperty instance from a string or object.
     */
    static createFrom($$source: any = {}): NodeProperty {
        const $$createField6_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField6_0($$parsedSource["options"]);
        }
        return new NodeProperty($$parsedSource as Partial<NodeProperty>);
    }
}

export enum PropertyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = 0,

    /**
     * Basic Types
     */
    Invalid = 0,
    Bool = 1,
    Int64 = 2,
    Uint64 = 3,
    Float64 = 4,
    String = 5,

    /**
     * Special Types
     */
    $JSON = 6,
    XML = 7,
    Date = 8,
    Text = 9,

    /**
     * Arrays
     */
    TextArray = 10,
    NumberArray = 11,
    BooleanArray = 12,
    JSONArray = 13,
    XMLArray = 14,
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
